version: '3.7'

services:
  chall:
    build:
      context: ./server
    ports:
      - "8888:8888"
    volumes:
      - ./attack:/output
    restart: always

  attacker:
    build:
      context: ./attack
    depends_on:
      - chall
    volumes:
      - ./attack:/output:cached
    networks:
      - default
