version: '3.7'

services:
  server:
    build:
      context: ./server
    ports:
      - "8888:8888"
    volumes:
      - ./attack:/output
    restart: "no"

  attacker:
    build:
      context: ./attack
    depends_on:
      - server
    volumes:
      - ./attack:/output:cached
    networks:
      - default
    restart: "no"
