version: '3.7'

services:
  server:
    build:
      context: .
    container_name: bsgs_server
    volumes:
      - ./server:/app
    working_dir: /app
    command: ["sage", "-python", "-u", "server.py"]
    ports:
      - "2026:2025"
    restart: unless-stopped

  attacker:
    image: sagemath/sagemath:latest
    container_name: bsgs_attacker
    depends_on:
      - server
    volumes:
      - ./attack:/attack
      - ./server:/data
    working_dir: /attack
    command: >
      bash -c "sage -pip install pycrypto &&
              sage -python -u attack.py"
    restart: unless-stopped
