version: '3.8'

services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: bsgs_server
    volumes:
      - ./server:/app
    working_dir: /app
    command: ["sage", "-python", "-u", "server.py"]
    restart: "no"

  attacker:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: bsgs_attacker
    depends_on:
      - server
    volumes:
      - ./attack:/attack
      - ./server:/data
    working_dir: /attack
    command: ["sage", "-python", "-u", "attack.py"]
    restart: "no"
